baseurl = "https://clairelouisebutler.com"
title = "Hugo Themes - aether"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 6
theme = "aether"
themesDir = "themes/" 

[params]
    brand = "Claire Louise Butler"
    description = "I am in interaction Designer in my final year of university."
    headshotimg = "img/faceshot.jpg"
    headshotalt = "Generic grey headshot picture"
    linkedin = "https://www.linkedin.com/in/claire-louise-butler/"
    instagram = "URL to your Instagram account, icon link will be included in the footer - optional"



[markup]
  [markup.highlight]
    style = "igor"