baseurl = "https://portfolio.clairelouisebutler.com"
title = "Claire Louise Butler"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 15
theme = "theme-test"
themesDir = "themes/" 
publishDir = "../public"

[params]
    brand = "Claire Louise Butler"
    description = "I am in interaction Designer in my final year of university."
    headshotimg = "img/faceshot.jpg"
    headshotalt = "Generic grey headshot picture"
    linkedin = "https://www.linkedin.com/in/claire-louise-butler/"
    instagram = "https://www.instagram.com/clairelouise.butler/?hl=en"
    spotify = "mailto:clairelouise.butler@outlook.com"



[markup]
  [markup.highlight]
    style = "igor"